# -*- coding: utf-8 -*-
"""EgyVed_BuktiPresensi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncPfXLxqmecDkAio73IS7CmiyEssDnIt

## Pengayaan (Load CSV)
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/adivii/datasets/main/Visualisasi%20Informasi/animated_tv_1987-2022.csv")
df

country = df['Country']

for i in range(2477):
    print(country[i].lower())

for i in country:
    print(i)

for i in range(2477):
    if df['Premiere Year'][i] > 2010:
        print(df['Title'][i])